name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarQube analysis

      # Grant execute permission to Gradle wrapper
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew
        working-directory: firstService

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # Build and Analyze with SonarQube
      - name: Build and Analyze
        env:
          SONAR_TOKEN: "sqp_240a80acfca1df514eb9a23ae66b313e64ada564"
          SONAR_HOST_URL: "https://924f-58-84-62-137.ngrok-free.app"
        run: ./gradlew build sonar --info
        working-directory: firstService
